### ISSUE TITLE
`RemoteError` should implement `Error`

### ISSUE THREAD

**Issue by ok-nick** [veeso/remotefs-rs#10]
Can't create higher-level errors without `RemoteError` implementing the `Error` trait or without manually picking out the `kind` field which I'm assuming isn't intentional.

**Comment by veeso** [comment]
Implemented in 0.2.0 as

```rust
use std::error::Error as StdError;

impl StdError for RemoteError {
    fn source(&self) -> Option<&(dyn StdError + 'static)> {
        Some(&self.kind)
    }
}
```
