### ISSUE TITLE
Combine the `File` and `Directory` struct

### ISSUE THREAD

**Issue by ok-nick** [veeso/remotefs-rs#3]
remote-fs has two separate structs for distinguishing files and directories which share both the same behavior and almost all the same fields. To account for this, it seems that the `Entry` enum was created to try and remove most of the boilerplate by combining the methods into one single enum. However, for the user, it ends up causing more boilerplate by forcing directory/file specific code when accessing entry fields which all function the same anyways.

remote-fs should combine both of the enum and both of these structs into a singular `File` struct that behaves similar to `std::fs::File`. The current `Directory`/`File` struct contains all the same fields except with the `File` struct having a unique `extension` field, which is optional anyway and I don't think is even necessary since you could derive that from the path (there could be an inlined method to shortcut this).

**Comment by veeso** [comment]
WIP PR #12
