### ISSUE TITLE
Decouple protocols into separate crates

### ISSUE THREAD

**Issue by ok-nick** [veeso/remotefs-rs#5]
I could see this as becoming more of a future issue, but having a module dedicated towards "natively-implemented drivers" could cause some versioning issues. Making a small change to just one protocol would mean an entire crate update. Most of the time this could mean waiting even longer before actually deploying the update so that there is more content, or it could mean an entire minor update that is unnecessary for many users.

Perhaps this is the plan for the future, but each protocol should be abstracted into its own crate. remote-fs could possibly re-export some of them, although that's not completely necessary and it could go back to the versioning issue I mentioned earlier.

**Comment by veeso** [comment]
It makes sense, so expect an update for this.

**Comment by veeso** [comment]
Released as separated crates:

<https://github.com/veeso/remotefs-rs-aws-s3>
<https://github.com/veeso/remotefs-rs-ftp>
<https://github.com/veeso/remotefs-rs-ssh>
