### ISSUE TITLE
Why `BufReader` and `BufWriter` wrapped returns on the `Sftp` and `Scp` protocols?

### ISSUE THREAD

**Issue by ok-nick** [veeso/remotefs-rs#6]
Wherever a trait object is returned in both of these protocols there is a `BufReader` or `BufWriter` wrapped with a capacity of `65536`.  I understand that this number is the maximum size of a TCP packet (which is actually `65535`?), but I don't see why it is enforced using these protocols?

What happens if the user wants to send 100 bytes? They can't because there is no way to flush the buffer since it is a trait object.

I think that the goal of this crate should be to provide a generic interface for all filesystem-like network protocols, and any additional abstractions or conveniences should be separated from the lowish-level interface.

**Comment by veeso** [comment]
Who knows 🤷🏻‍♂️ 

At the time I made some benchmarks to test the best buffer size and I noticed the fastest way to transfer bytes to the remote server was by wrapping the handler into a BufIo with the size of 65536. I tested many cases, 65535 too, but they perform worse.

The maximum packet size for ssh is 32KB anyway as far as I know, but using a buffer with a capacity of 32KB performs worse too.

If I give users the raw handler, I can bet that hundreds of issues like "extremely slow transfer with sftp" would appear, so I'd like to keep it as-is.

> What happens if the user wants to send 100 bytes? They can't because there is no way to flush the buffer since it is a trait object.

That's not true, the capacity and the length are two different stuff. You can send how many bytes you like.

**Comment by ok-nick** [comment]
There are a lot of factors that  influence the perfect buffer size and it's really dependent on hardware, network, latency, sector size, etc. It's not possible to assume the best size for everyone.

Also, the people who use this crate and language should know what they are doing. If they want the best performance, then they should be able to optimize to reach the best performance, remote-fs shouldn't restrict them. You could suggest in the documentation to wrap it in a BufWriter of x size and the user could do so if necessary. Otherwise, you could provide a separate abstraction that the user could optionally use if it is a common pattern.

Buffered IO traits only flush when the length reaches at or past the set capacity. So it wouldn't be possible to send 100 bytes unless if you drop the trait object which calls an implicit flush to the BufWriter. This isn't always desirable if you want to handle errors or if you want to send exactly 100 bytes at that exact moment.

**Comment by veeso** [comment]
You always drop the buffer though, since you must call the finalizing methods when dealing with write/read on remote fs. I'll keep this issue in pause at the moment, since I still need to investigate whether there are better combinations for the buffers than 65KB

**Comment by ok-nick** [comment]
For a connection like Sftp there are no finalizing methods for reading and writing. You'd have to drop the buffer to flush it which disallows you from handling errors.

**Comment by veeso** [comment]
I performed further tests and you're right, it seems that bufreader/bufwriter is not necessary at all:

I ran the following program using both the current main branch and a branch without buffers and times are equal.
But the 65535 is still a magic number in terms of performance. If you change BFUSIZE to anything else, the transfer will be slower.

```rust
use remotefs::client::ssh::{ScpFs, SftpFs, SshOpts};
use remotefs::fs::Metadata;
use remotefs::RemoteFs;
use std::env;
use std::fs::File;
use std::io::{Read, Seek};
use std::path::Path;
use std::time::{Duration, Instant};

const BUFSIZE: usize = 65535;

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 5 {
        panic!("Usage: <ssh-host> <port> <username> <password> [cycles]");
    }
    let hostname = &args[1];
    let port = args.get(2).map(|x| x.parse::<u16>().ok().unwrap()).unwrap();
    let username = &args[3];
    let password = &args[4];
    let cycles = args
        .get(5)
        .map(|x| x.parse::<usize>().ok().unwrap())
        .unwrap_or(10);
    env_logger::init();
    // sftp
    let client: SftpFs = SshOpts::new(hostname)
        .port(port)
        .username(username)
        .password(password)
        .into();
    run_test("SFTP", client, cycles);
    // scp
    let client: ScpFs = SshOpts::new(hostname)
        .port(port)
        .username(username)
        .password(password)
        .into();
    run_test("SCP", client, cycles);
}

fn run_test(name: &str, mut client: impl RemoteFs, cycles: usize) {
    let dest = Path::new("/tmp/test.bin");
    println!("TEST: {}", name);
    assert!(client.connect().is_ok());
    let mut avg = Duration::ZERO;
    // Loop over cycles
    for n in 0..cycles {
        let mut file =
            File::open("/tmp/data.bin").expect("You need to put a file /tmp/data.bin to run this");
        let file_size: u64 = file.seek(std::io::SeekFrom::End(0)).unwrap_or(0);
        // rewind
        file.seek(std::io::SeekFrom::Start(0))
            .expect("Could not rewind");
        let t_start = Instant::now();
        let mut writer = client
            .create(dest, &Metadata::default().size(file_size))
            .ok()
            .unwrap();
        let mut bytes: usize = 0;
        while bytes < (file_size as usize) {
            let mut buffer: [u8; BUFSIZE] = [0; BUFSIZE];
            let bytes_read = file.read(&mut buffer).expect("Could not read file");
            let mut delta = 0;
            while delta < bytes_read {
                delta += writer
                    .write(&buffer[delta..bytes_read])
                    .expect("failed to write stream");
            }
            bytes += bytes_read;
        }
        avg += t_start.elapsed();
        println!(
            "Cycle {:02} took {}us ({}ms)",
            n + 1,
            t_start.elapsed().as_micros(),
            t_start.elapsed().as_millis()
        );
        assert!(client.remove_file(dest).is_ok());
    }
    let avg = avg / (cycles as u32);
    println!(
        "Average time: {}us ({}ms)",
        avg.as_micros(),
        avg.as_millis()
    );
    assert!(client.disconnect().is_ok());
}
```

So I will remove buffers in the next version.
