### ISSUE TITLE
Cleanup dependencies

### ISSUE THREAD

**Issue by ok-nick** [veeso/remotefs-rs#8]
Many of the dependencies could be optional, `wildmatch`, `lazy_static`, `regex`. Also not too sure about the use for the `log` crate. And the `thiserror` crate is only used once, so I don't think that is even necessary.
The currently optional dependencies could be removed and put into separate crates as described in #5.

**Comment by veeso** [comment]
Hi,

Optional dependencies make sense actually. Some of them are not optional in my opinion. Wildmatch is required for executing `find`, which could be made into a feature, but it's not really a huge crate, so I'm not going to make it a feature.
Thiserror is used once, but I use it as a standard in my projects, so I'll keep it anyway.

**Comment by ok-nick** [comment]
I think it's best to have as much modularity and optionality as possible; let the user take full advantage of what they possibly can.

I'd suggest making wildmatch optional behind a feature flag and setting it as a default feature (questionable?). I'm sure most people aren't going to be using the find method anyways so it could help get rid of unnecessary code and lower compile times.

**Comment by veeso** [comment]
I made `find` as a feature, so wildmatch is now an optional dependency. I'd say everything is fine for this issue.
