### ISSUE TITLE
Implement `Seek` trait for readers

### ISSUE THREAD

**Issue by ok-nick** [veeso/remotefs-rs#9]
I remember you stating that you intentionally excluded the `Seek` trait because [remote files don't have this](https://github.com/veeso/termscp/issues/69#issuecomment-935621215), however, this is not true. Protocols like SFTP do have methods for seeking in a file and it only makes sense, what if you wanted to read or write 5 bytes from the center of a file? It's true that some protocols don't have methods for seeking through files, although this could easily be abstracted. I think it's important here to allow users to have as much functionality as possible.

I understand that in a protocol like FTP, it's practically impossible to implement seeking without reading through the entire file (a lot of servers actually support this). Yes, this could be abstracted, but at a significant cost. I think the best route to account for this would be doing something like `chicon-rs`, if you recall. Instead of returning a trait object from a method like `open`, it could rather be a new struct resembling a file. Then it would be up to the user to implement seeking or not. This method sounds nice, but I guess it kinda ruins the "generic" `RemoteFs` trait.
The reason I suggested returning a file struct instead of a trait object which also includes `Seek` is because I think it would offer a more convenient API. Getting a little offtopic here, but I like how the `ssh2` crate returns a `File` struct that you can call other methods on, like getting metadata, for example. It just makes for a little more convenient and nicer API for the user.

Option three would just be to go with option one while making sure everything is carefully documented. I'm not too fond of the idea of faking traits and misusing them which is why I don't think this is the way to go. I think it would be confusing even if it was completely documented.

Overall, I think option two is the way to go to maximize functionality, performance, and convenience. As I said, it would kind of ruin the generic interface, but in a situation like this where it's really dependent on the protocol, I think it's necessary.

**Comment by ok-nick** [comment]
Rethinking it, I disagree with option two, it's important to keep everything generic and option one would be the way to go.  The user should __have to__ return something implementing `Seek` and if it's not supported then there is no reason to fake it. Rather, the user could error in each method, returning [ErrorKind::Unsupported](https://doc.rust-lang.org/stable/std/io/enum.ErrorKind.html).

**Comment by ok-nick** [comment]
Even better, [ErrorKind::NotSeekable](https://doc.rust-lang.org/stable/std/io/enum.ErrorKind.html#variant.NotSeekable).

**Comment by ok-nick** [comment]
Rethinking this again, I agree with option two. The `RemoteFs` trait could use a GAT that looks something like this,
```rs
type File<T: Read + Write + Seek>;
```
I don't think GAT's are completely stabilized yet, but there shouldn't be anything blocking or unimplemented for them with this code. The goal is for the user to define their own `File` struct which implements all three of these traits. Let's say they don't support seeking (reevaluating this, basically all protocols support some type of seeking), then simple fix, do what I mentioned above and return `ErrorKind::NotSeekable` or `ErrorKind::Unsupported`. One huge benefit about this design is that you could go ham with whatever you want. Adding your own unique methods is now doable for each individual file if your protocol has something unique. With FTP, for example, instead of having an `on_read` and all those other nasty ugly methods, you could implement `Drop` and implicitly finalize the stream. This is definitely safer, although it'd still be recommended to explicitly finalize it anyways (I suggest changing `on_read` to something like `finalize_read`) which could now be called directly from the new `File` struct. On top of everything, the "generic interface" that I was so keen on is still preserved. With the GAT, users are guaranteed that the `Read` and `Write` and `Seek` traits are implemented.

**Comment by veeso** [comment]
What about this #13 PR? I think this should work.

**Comment by veeso** [comment]
This solution is currently working fine in the client implementation, so I mark it as done.
